# Generated by Django 5.0 on 2023-12-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_student_first_name_student_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_officer',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dean',
            name='signature_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hod',
            name='signature_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reg_officer',
            name='signature_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
