# Generated by Django 5.0 on 2023-12-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_reg_officer_name_alter_dean_signature_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dean',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hod',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
